export const ICON_MAP: Record<string, string> = {
  ShoppingCart: "🛒",
  Heart: "❤️",
  House: "🏠",
  Car: "🚗",
  Plane: "✈️",
  Gift: "🎁",
  Book: "📚",
  Music: "🎵",
  Gamepad2: "🎮",
  Dog: "🐶",
  Dumbbell: "🏋️",
  Stethoscope: "🩺",
  GraduationCap: "🎓",
  Wrench: "🛠️",
  Baby: "👶",
  Coffee: "☕",
  Shirt: "👕",
  Sparkles: "✨",
  Monitor: "🖥️",
  Scissors: "✂️",
  Wallet: "👛",
  Umbrella: "☂️",
  Briefcase: "💼",
  PiggyBank: "🐷",
  Trophy: "🏆",
  Star: "⭐",
  Zap: "⚡",
  Wifi: "📶",
  Fuel: "⛽",
  Wine: "🍷",
  ShoppingBag: "🛍️",
  Building2: "🏢",
  PawPrint: "🐾",
  Smartphone: "📱",
  TrendingUp: "📈",
  Utensils: "🍽️",
};

export const SELECTABLE_ICONS: readonly { readonly name: string; readonly icon: string }[] =
  Object.entries(ICON_MAP).map(([name, icon]) => ({ name, icon }));
