import { StyleSheet } from "@/shared/components/rn";

export const styles = StyleSheet.create({
  container: {},
  scrollContent: { padding: 24, gap: 16 },
  title: { fontFamily: "Poppins_700Bold", fontSize: 18, textAlign: "center" },
  toggleRow: { flexDirection: "row", gap: 8 },
  toggleButton: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleText: { fontFamily: "Poppins_600SemiBold", fontSize: 13 },
  fieldGroup: { gap: 4 },
  fieldLabel: { fontFamily: "Poppins_500Medium", fontSize: 12, fontStyle: "italic" },
  input: {
    height: 48,
    borderRadius: 12,
    borderCurve: "continuous",
    borderWidth: 1,
    paddingHorizontal: 16,
    fontFamily: "Poppins_500Medium",
    fontSize: 14,
  },
  dateButton: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dateText: { fontFamily: "Poppins_500Medium", fontSize: 14 },
  clearDateText: { fontSize: 14 },
  amountSection: { alignItems: "center", gap: 4, paddingVertical: 8 },
  amountRow: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
  amountDisplay: { fontFamily: "Poppins_700Bold", fontSize: 32 },
  interestInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  interestInput: { flex: 1 },
  interestSuffix: { fontFamily: "Poppins_700Bold", fontSize: 18 },
  cursor: { width: 2, height: 28, marginLeft: 2, borderRadius: 1 },
  projectionHint: { fontFamily: "Poppins_500Medium", fontSize: 13, textAlign: "center" },
  actionButton: {
    borderRadius: 12,
    borderCurve: "continuous",
    paddingVertical: 14,
    alignItems: "center",
    minHeight: 48,
  },
  destructiveActionButton: {
    borderWidth: 1.5,
  },
  actionButtonText: { fontFamily: "Poppins_700Bold", fontSize: 16, color: "#FFFFFF" },
  destructiveActionButtonText: { fontFamily: "Poppins_700Bold", fontSize: 16 },
});
