export const CRAP_SRC = [
  "features/account-suggestions",
  "features/activity",
  "features/advisor",
  "features/ai-chat",
  "features/analytics",
  "features/auth",
  "features/background-fetch",
  "features/backup",
  "features/budget",
  "features/calendar",
  "features/capture-evidence",
  "features/capture-interpreter",
  "features/capture-sources",
  "features/categories",
  "features/dashboard",
  "features/email-capture",
  "features/financial-accounts",
  "features/goals",
  "features/notifications",
  "features/onboarding",
  "features/qa",
  "features/review-queues",
  "features/search",
  "features/settings",
  "features/transactions",
  "features/transfers",
  "shared/constants",
  "shared/hooks",
  "shared/i18n",
  "shared/lib",
  "shared/mutations",
  "shared/types",
];

export const CRAP_EXCLUDE = ["**/components/**", "**/ui/**", "**/*.tsx"];
