import nativewindPreset from "nativewind/preset";
import type { Config } from "tailwindcss";
import { Colors } from "./shared/constants/theme";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./features/**/*.{ts,tsx}", "./shared/**/*.{ts,tsx}"],
  presets: [nativewindPreset],
  theme: {
    extend: {
      colors: {
        page: Colors.light.page,
        "page-dark": Colors.dark.page,
        background: Colors.light.background,
        "background-dark": Colors.dark.background,
        primary: Colors.light.primary,
        "primary-dark": Colors.dark.primary,
        "text-primary": Colors.light.textPrimary,
        "text-primary-dark": Colors.dark.textPrimary,
        secondary: Colors.light.secondary,
        "secondary-dark": Colors.dark.secondary,
        "text-secondary": Colors.light.textSecondary,
        "text-secondary-dark": Colors.dark.textSecondary,
        tertiary: Colors.light.tertiary,
        "tertiary-dark": Colors.dark.tertiary,
        "text-tertiary": Colors.light.textTertiary,
        "text-tertiary-dark": Colors.dark.textTertiary,
        "accent-green": Colors.light.accentGreen,
        "accent-green-dark": Colors.dark.accentGreen,
        "action-primary": Colors.light.actionPrimary,
        "action-primary-dark": Colors.dark.actionPrimary,
        success: Colors.light.success,
        "success-dark": Colors.dark.success,
        "accent-green-light": Colors.light.accentGreenLight,
        "accent-green-light-dark": Colors.dark.accentGreenLight,
        "accent-red": Colors.light.accentRed,
        "accent-red-dark": Colors.dark.accentRed,
        danger: Colors.light.danger,
        "danger-dark": Colors.dark.danger,
        warning: Colors.light.warning,
        "warning-dark": Colors.dark.warning,
        "text-on-accent": Colors.light.textOnAccent,
        "text-on-accent-dark": Colors.dark.textOnAccent,
        card: Colors.light.card,
        "card-dark": Colors.dark.card,
        surface: Colors.light.surface,
        "surface-dark": Colors.dark.surface,
        "peach-light": Colors.light.peachLight,
        "peach-light-dark": Colors.dark.peachLight,
        "surface-muted": Colors.light.surfaceMuted,
        "surface-muted-dark": Colors.dark.surfaceMuted,
        "surface-raised": Colors.light.surfaceRaised,
        "surface-raised-dark": Colors.dark.surfaceRaised,
        "chart-bg": Colors.light.chartBg,
        "chart-bg-dark": Colors.dark.chartBg,
        nav: Colors.light.nav,
        "nav-dark": Colors.dark.nav,
        "chart-food": Colors.chart.food,
        "chart-transport": Colors.chart.transport,
        "chart-entertainment": Colors.chart.entertainment,
        "chart-health": Colors.chart.health,
        "chart-education": Colors.chart.education,
        "chart-home": Colors.chart.home,
        "chart-clothing": Colors.chart.clothing,
        "chart-services": Colors.chart.services,
        "chart-transfer": Colors.chart.transfer,
        "chart-other": Colors.chart.other,
        "login-bg": Colors.light.loginBg,
        "login-bg-dark": Colors.dark.loginBg,
        "login-google": Colors.light.loginGoogle,
        "login-google-dark": Colors.dark.loginGoogle,
        "login-google-border": Colors.light.loginGoogleBorder,
        "login-google-border-dark": Colors.dark.loginGoogleBorder,
        "login-ms": Colors.light.loginMs,
        "login-ms-dark": Colors.dark.loginMs,
        "border-subtle": Colors.light.borderSubtle,
        "border-subtle-dark": Colors.dark.borderSubtle,
        "border-strong": Colors.light.borderStrong,
        "border-strong-dark": Colors.dark.borderStrong,
        "chat-assistant-bubble": Colors.light.chatAssistantBubble,
        "chat-assistant-bubble-dark": Colors.dark.chatAssistantBubble,
        "chat-assistant-text": Colors.light.chatAssistantText,
        "chat-assistant-text-dark": Colors.dark.chatAssistantText,
        "chat-user-bubble": Colors.light.chatUserBubble,
        "chat-user-bubble-dark": Colors.dark.chatUserBubble,
        "chat-user-text": Colors.light.chatUserText,
        "chat-user-text-dark": Colors.dark.chatUserText,
        "accent-red-light": `${Colors.light.accentRed}11`,
        "accent-red-light-dark": `${Colors.dark.accentRed}11`,
        "peach-btn": Colors.light.numpadSpecialKey,
        "peach-btn-dark": Colors.dark.numpadKey,
      },
      fontFamily: {
        poppins: ["Poppins_400Regular"],
        "poppins-medium": ["Poppins_500Medium"],
        "poppins-semibold": ["Poppins_600SemiBold"],
        "poppins-bold": ["Poppins_700Bold"],
        "poppins-extrabold": ["Poppins_800ExtraBold"],
      },
      fontSize: {
        nav: ["10px", { lineHeight: "14px" }],
        caption: ["12px", { lineHeight: "16px" }],
        label: ["13px", { lineHeight: "18px" }],
        body: ["14px", { lineHeight: "20px" }],
        section: ["16px", { lineHeight: "22px" }],
        title: ["18px", { lineHeight: "24px" }],
        logo: ["22px", { lineHeight: "28px" }],
        balance: ["32px", { lineHeight: "40px" }],
      },
      borderRadius: {
        icon: "12px",
        chart: "16px",
        "nav-pill": "36px",
      },
    },
  },
  plugins: [],
};

export default config;
