import nativewindPreset from "nativewind/preset";
import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./features/**/*.{ts,tsx}", "./shared/**/*.{ts,tsx}"],
  presets: [nativewindPreset],
  theme: {
    extend: {
      colors: {
        page: "#FAEBD7",
        "page-dark": "#0D0D0D",
        primary: "#1A1A1A",
        "primary-dark": "#F0F0F0",
        secondary: "#6D6D6D",
        "secondary-dark": "#9A9A9A",
        tertiary: "#929292",
        "tertiary-dark": "#5E5E5E",
        "accent-green": "#7CB243",
        "accent-green-dark": "#8BC34A",
        "accent-green-light": "#D4EDBA",
        "accent-green-light-dark": "#1A2E12",
        "accent-red": "#D45B5B",
        "accent-red-dark": "#E06060",
        card: "#FFFFFF",
        "card-dark": "#1C1C1E",
        "peach-light": "#F5E1C8",
        "peach-light-dark": "#2A1F1A",
        "chart-bg": "#F5E1C8",
        "chart-bg-dark": "#2A1F1A",
        nav: "#1A1A1A",
        "nav-dark": "#1C1C1E",
        "chart-food": "#7CB243",
        "chart-transport": "#E8A090",
        "chart-entertainment": "#F5C842",
        "chart-health": "#E06060",
        "chart-education": "#5B9BD5",
        "chart-home": "#8BBAE8",
        "chart-clothing": "#1A1A1A",
        "chart-services": "#F0A04B",
        "chart-transfer": "#6DC4B0",
        "chart-other": "#B8A9D4",
        "login-bg": "#EDECEA",
        "login-bg-dark": "#0D0D0D",
        "login-google": "#FFFFFF",
        "login-google-dark": "#1C1C1E",
        "login-google-border": "#E5E2DC",
        "login-google-border-dark": "#3A3A3C",
        "login-ms": "#F3F2EE",
        "login-ms-dark": "#2C2C2E",
        "border-subtle": "#EBEBEB",
        "border-subtle-dark": "#2C2C2E",
        "accent-red-light": "#D45B5B11",
        "accent-red-light-dark": "#E0606011",
        "peach-btn": "#FAE3D9",
        "peach-btn-dark": "#2A1F1A",
      },
      fontFamily: {
        "poppins-medium": ["Poppins_500Medium"],
        "poppins-semibold": ["Poppins_600SemiBold"],
        "poppins-bold": ["Poppins_700Bold"],
        "poppins-extrabold": ["Poppins_800ExtraBold"],
      },
      fontSize: {
        nav: ["10px", { lineHeight: "14px" }],
        caption: ["12px", { lineHeight: "16px" }],
        label: ["13px", { lineHeight: "18px" }],
        body: ["14px", { lineHeight: "20px" }],
        section: ["16px", { lineHeight: "22px" }],
        title: ["18px", { lineHeight: "24px" }],
        logo: ["22px", { lineHeight: "28px" }],
        balance: ["32px", { lineHeight: "40px" }],
      },
      borderRadius: {
        icon: "12px",
        chart: "16px",
        "nav-pill": "36px",
      },
    },
  },
  plugins: [],
};

export default config;
