import { resolve } from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(__dirname, "."),
    },
  },
  test: {
    environment: "node",
    globals: false,
    clearMocks: true,
    testTimeout: 60000,
    setupFiles: ["./__tests__/setup.ts"],
    include: ["__tests__/**/*.test.ts"],
    server: {
      deps: {
        inline: [/expo-sqlite/],
        external: [
          /react-native/,
          /react-native-safe-area-context/,
          /react-native-svg/,
          /@react-navigation/,
          /@react-native-community/,
        ],
      },
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary"],
      include: [
        "features/**/lib/**",
        "features/**/data/**",
        "features/email-capture/schema.ts",
        "features/email-capture/services/**",
        "features/email-capture/store.ts",
        "features/email-capture/store/**",
        "features/onboarding/store.ts",
        "features/transactions/schema.ts",
        "features/transactions/store.ts",
        "features/ai-chat/schema.ts",
        "features/ai-chat/lib/**",
        "features/calendar/schema.ts",
        "features/calendar/store.ts",
        "features/menu/store.ts",
        "shared/constants/theme.ts",
        "shared/hooks/use-theme-color.ts",
        "shared/hooks/create-async-guard.ts",
        "shared/components/navigation/tab-config.ts",
      ],
      exclude: [
        "features/email-capture/store.ts",
        "features/email-capture/store/**",
        "features/email-capture/lib/financial-meaning-review.ts",
        "features/email-capture/lib/source-event-repository.ts",
        "features/email-capture/lib/source-event-review-repository.ts",
        "features/email-capture/services/email-capture-store-runtime.ts",
      ],
      thresholds: {
        statements: 82,
        branches: 82,
        functions: 82,
        lines: 82,
        "features/email-capture/lib/merchant-rules.ts": { 100: true },
        "features/email-capture/services/create-email-adapter.ts": { 100: true },
        "features/email-capture/services/create-email-pipeline-service.ts": { 100: true },
        "features/email-capture/services/email-adapter-registry.ts": { 100: true },
        "features/email-capture/services/email-capture-sync-policy.ts": { 100: true },
        "features/email-capture/services/email-parse-improvement-sharing.ts": { 100: true },
        "features/email-capture/services/email-pipeline.ts": { 100: true },
        "features/email-capture/services/email-pipeline-service/parse-improvement.ts": {
          100: true,
        },
        "features/email-capture/services/email-pipeline-service/transactions.ts": { 100: true },
        "features/email-capture/services/gmail-adapter.ts": { 100: true },
        "features/email-capture/services/llm-parser.ts": { 100: true },
        "features/email-capture/services/outlook-adapter.ts": { 100: true },
        "features/email-capture/services/parse-email-service.ts": { 100: true },
        "features/onboarding/lib/**": { 100: true },
        "features/onboarding/store.ts": { 100: true },
        "shared/hooks/create-async-guard.ts": { 100: true },
      },
    },
  },
});
