import { StyleSheet } from "@/shared/components/rn";

export const styles = StyleSheet.create({
  container: {},
  scrollContent: {
    paddingTop: 12,
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 16,
  },
  title: {
    fontFamily: "Poppins_600SemiBold",
    fontSize: 16,
    textAlign: "center",
  },
  previewRow: { alignItems: "center" },
  previewPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 48,
    paddingVertical: 10,
    paddingLeft: 16,
    paddingRight: 20,
    borderRadius: 24,
    borderCurve: "continuous",
  },
  previewIcon: {
    fontSize: 18,
    lineHeight: 22,
  },
  previewText: {
    fontFamily: "Poppins_600SemiBold",
    fontSize: 15,
  },
  fieldGroup: { gap: 8 },
  fieldLabel: {
    fontFamily: "Poppins_500Medium",
    fontSize: 13,
  },
  input: {
    borderRadius: 12,
    borderCurve: "continuous",
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontFamily: "Poppins_400Regular",
    fontSize: 14,
  },
  customEmojiField: { gap: 8, marginBottom: 12 },
  customEmojiInput: { fontSize: 20 },
  iconGridContent: { gap: 8 },
  iconGridRow: { gap: 8, justifyContent: "flex-start" },
  iconCellWrapper: { flex: 1, alignItems: "center" },
  iconCell: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  swatchGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  swatch: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  createButton: {
    borderRadius: 12,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    height: 48,
  },
});
