const fs = require("node:fs");
const path = require("node:path");

const EXTENSION_NAME = "FidyWidgetExtension";
const DEPLOYMENT_TARGET = "26.0";
const SWIFT_VERSION = "6.0";

const SWIFT_FILES = [
  "QuickExpenseIntent.swift",
  "FidyCategory.swift",
  "TransactionKind.swift",
  "FidyWidgetBundle.swift",
  "WidgetConfig.swift",
];

const STATIC_EXTENSION_FILES = [
  "QuickExpenseIntent.swift",
  "FidyCategory.swift",
  "TransactionKind.swift",
  "FidyWidgetBundle.swift",
  "widget.entitlements",
];

const getDevelopmentTeam = (config) => config.ios?.developmentTeam ?? "";
const getAppGroup = (config) => `group.${config.ios?.bundleIdentifier ?? "com.obarbozaa.Fidy"}`;
const getExtensionBundleId = (config) =>
  `${config.ios?.bundleIdentifier ?? "com.obarbozaa.Fidy"}.WidgetExtension`;

const buildWidgetConfigContent = (appGroup) =>
  [
    "// Auto-generated by withFidyWidget — do not edit manually.",
    `let APP_GROUP_SUITE_NAME = "${appGroup}"`,
    'let PENDING_TRANSACTIONS_KEY = "pendingWidgetTransactions"',
    "",
  ].join("\n");

const copyWidgetFiles = (projectRoot, config) => {
  const sourceDir = path.join(projectRoot, "targets", "widget");
  const destDir = path.join(projectRoot, "ios", EXTENSION_NAME);
  const appGroup = getAppGroup(config);

  fs.mkdirSync(destDir, { recursive: true });

  for (const file of STATIC_EXTENSION_FILES) {
    fs.copyFileSync(path.join(sourceDir, file), path.join(destDir, file));
  }

  fs.writeFileSync(path.join(destDir, "WidgetConfig.swift"), buildWidgetConfigContent(appGroup));
  fs.copyFileSync(
    path.join(sourceDir, "Info.plist"),
    path.join(destDir, `${EXTENSION_NAME}-Info.plist`)
  );
};

module.exports = {
  buildWidgetConfigContent,
  copyWidgetFiles,
  deploymentTarget: DEPLOYMENT_TARGET,
  extensionName: EXTENSION_NAME,
  getAppGroup,
  getDevelopmentTeam,
  getExtensionBundleId,
  staticExtensionFiles: STATIC_EXTENSION_FILES,
  swiftFiles: SWIFT_FILES,
  swiftVersion: SWIFT_VERSION,
};
