name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - "apps/landing/**"

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Pull Vercel config
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/landing
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to production
        id: deploy
        run: |
          deployment_url="$(vercel deploy --prod --skip-domain --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1)"
          echo "url=$deployment_url" >> "$GITHUB_OUTPUT"
          echo "$deployment_url"
        working-directory: apps/landing
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Fluid Attacks DAST
        working-directory: apps/landing
        run: |
          cat > fluidattacks-dast.config.yaml << 'EOF'
          strict: true
          namespace: fidy-landing
          output:
            file_path: /tmp/fluid-attacks-results.csv
            format: CSV
          dast:
            strict_connectivity: true
            urls:
              - url: ${{ steps.deploy.outputs.url }}
          EOF

          docker run --rm -v "$PWD:/scan-root" docker.io/fluidattacks/dast@sha256:c2b70826369c89086ce5ead62438725d1991a2f8a120007d318f3d2ef9c03448 dast --strict scan /scan-root/fluidattacks-dast.config.yaml

          rm fluidattacks-dast.config.yaml

      - name: Promote production deployment
        run: |
          vercel promote "${{ steps.deploy.outputs.url }}" --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: apps/landing
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
